version: "3.10"
services:
  worker:
    build: .
    environment:
       API_ID: $API_ID
       API_HASH: $API_HASH
       BOT_TOKEN: $BOT_TOKEN
       MONGO_DB_URI: $MONGO_DB_URI
       LOG_GROUP_ID: $LOG_GROUP_ID
       MUSIC_BOT_NAME: $MUSIC_BOT_NAME
       STRING_SESSION: $STRING_SESSION
       OWNER_ID: $OWNER_ID
       SUPPORT_CHANNEL: $SUPPORT_CHANNEL
       SUPPORT_GROUP: $SUPPORT_GROUP
